name: CI Workflow

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PYTHONPATH: .
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch
          # Тут можно добавлять любые дополнительные зависимости, если потребуется

      - name: Create environment and install project
        run: |
          hatch env create
          hatch run pip install -e .

      - name: Run linter (ruff)
        run: |
          hatch run ruff .

      - name: Run tests
        run: |
          hatch run pytest --maxfail=1 --disable-warnings

      - name: Run test coverage
        run: |
          hatch run pytest --maxfail=1 --disable-warnings --cov=gendiff

      - name: Run SonarQube Scan (только на ветке main)
        if: github.ref == 'refs/heads/main'
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectKey: Grimmlok626_python-project-50