name: CI

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      PYTHONPATH: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install hatch
        run: |
          python -m pip install --upgrade pip
          pip install hatch

      - name: Create environment and install dev dependencies
        run: |
          hatch env create
          hatch run pip install -e .[dev]

      - name: Run tests with coverage
        run: |
          PYTHONPATH=${GITHUB_WORKSPACE} hatch run -- python -m pytest --maxfail=1 --disable-warnings --cov=gendiff --cov-report=xml:coverage.xml

      - name: Run ruff (linter)
        run: |
          PYTHONPATH=${GITHUB_WORKSPACE} hatch run -- python -m ruff .

      - name: SonarCloud scan
        if: github.ref == 'refs/heads/main'
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectKey: Grimmlok626_python-project-50
          organization: Grimmlok626
          host-url: https://sonarcloud.io