name: Python CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install -U pip
          pip install -r requirements.txt
          # или, если используете make install:
          # make install
      - name: Run linter
        run: make lint
      - name: Run tests
        run: bash -c "PYTHONPATH=src make test"
      - name: Run test coverage
        run: bash -c "PYTHONPATH=src make test-coverage"
      - name: SonarQubeScan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=python-project-50
            -Dsonar.organization=grimmlok626
            -Dsonar.python.coverage.reportPaths=coverage.xml
