name: Python CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies with hatch
        run: |
          pip install --upgrade pip
          pip install hatch
          hatch env create
          hatch develop

      - name: Run linter
        run: |
          hatch run make lint

      - name: Run tests
        run: |
          hatch run make test

      - name: Run test coverage
        run: |
          hatch run make test-coverage